name: PYZA
favicon: null
layout_spectrum: 0.1411678115837276
typography_spectrum: 0.6081909697968513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6216582148335874
  lightness: 0.6745200061704963
  saturation: 0.6635092701762915
  rhythmicContrast: 0.5068704870063812
purpose: []
