name: PYZA
favicon: null
layout_spectrum: 0.65452
typography_spectrum: 0.6081909697968513
title: PYZAA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#000000'
    - '#121212'
    - '#171717'
    - '#240000'
  brandStrength: 0.6216582148335874
  lightness: 0.6745200061704963
  saturation: 0.625
  rhythmicContrast: 0.5068704870063812
purpose: []
